### ISSUE TITLE
Not starting again

### ISSUE THREAD

**Issue by WreckagePE** [Viperize/RestartMe-PocketMine#1]
Server restarts as normal, receives stop command but does not start again. I can only start it again from console.

**Comment by ifvictr** [comment]
Did you make sure to have the auto-restart script installed properly?

**Comment by WreckagePE** [comment]
I just installed the plugin. It used to work fine, however I have encountered this problem recently

**Comment by ifvictr** [comment]
You **need** to install the restart script in order for the server to restart. The script is the most critical part of the entire thing.

**Comment by WreckagePE** [comment]
How do I install the script?

**Comment by ifvictr** [comment]
Instructions are at https://forums.pocketmine.net/plugins/restartme.1509/, under the usage section.

**Comment by Patra3** [comment]
@ifvictr The page is unavailable...

**Comment by ifvictr** [comment]
Looks like @shoghicp forgot to renew the SSL certificate... Try http://forums.pocketmine.net/plugins/restartme.1509/ instead.
